### ISSUE TITLE
HTML structuur

### ISSUE THREAD

**Issue by koeenm** [TygoWolven/the-startup-responsive-interactieve-website#1]
Ik kan goed begrijpen hoe de html in elkaar zit. Class namen hebben een goede benaming en de structuur valt ook niks op aan te merken.

Ik begrijp alleen niet wat de verschillen zijn tussen search-button en search-button2 maar eigenlijk is er niks op aan te merken

Semantiek is heel goed

**Comment by TygoWolven** [comment]
Dat was even een snelle oplossing om de navigatiebalk responsive te maken, daar ga ik mij nog op focussen. Thanks voor de herinnering!
