### ISSUE TITLE
Code en design review

### ISSUE THREAD

**Issue by lisavanmansom** [TygoWolven/the-startup-responsive-interactieve-website#2]
Html tip:

- lang= nl ---- de website is Nederlands, daarom zou ik ook de language op nl zetten.

https://github.com/TygoWolven/the-startup-responsive-interactieve-website/blob/3a61b2778b835dfb137d8b855f8e14b434589d71/index.html#L2

Html & CSS top:

- Code overzichtelijk door comments;
- Duidelijke structuur doorgevoerd in beide bestanden waardoor het makkelijk is om te begrijpen wat er is gedaan en oogt het overzichtelijk.

**Comment by TygoWolven** [comment]
Helemaal gelijk over de taal, direct aangepast! Bedankt voor de tops. :)
