### ISSUE TITLE
CSS en mobile first

### ISSUE THREAD

**Issue by koeenm** [TygoWolven/the-startup-responsive-interactieve-website#3]
Heel goed notities toegevoegd zodat ik zie waar een stukje css voor dient dat maakt het heel duidelijk en als ik nu hieraan zou werken zou ik gelijk weten waar ik kan werken

Heel goed de css genest en  een goede structuur

De website is niet mobile first gemaakt dus is hij, nu nog, niet te gebruiken op mobiel

**Comment by TygoWolven** [comment]
Ik heb de pagina volledig responsive gemaakt, vanaf nu ook op mobiel te gebruiken!
