### ISSUE TITLE
A vervangen in je dropdown menu

### ISSUE THREAD

**Issue by Seijno** [TygoWolven/the-startup-responsive-interactieve-website#6]
``` HTML
<a href="#" id="radio-dropdown">
                    Radio 
                    <i class='bx bx-chevron-down' id="chevron-down"></i>
                    <ul class="dropdown">
                        <li><a href="https://www.bnr.nl/radio">Nu op de radio</a></li>
                        <li><a href="https://www.bnr.nl/programmagids">Programmagids</a></li>
                        <li><a href="https://www.bnr.nl/gemist">Gemist</a></li>
                    </ul>
                </a>
```
omdat je de dropdown met een a tag doet krijg je veel foutmeldingen, verander dit en je hebt het gefixt. 
Je kan proberen de a te vervangen met een Button.

**Comment by TygoWolven** [comment]
De reden dat het een link is, is voor de styling. Alle styling staat op de navigatie-links, en als dus de dropdown geen link zou hebben valt de styling compleet uit elkaar. Mogelijk kan ik dit op een andere manier oplossen, bedankt voor de heads-up iedergeval!
